version: '3.8'

services:

  db:
    image: postgres:16.3
#    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=$DBPassword
      - POSTGRES_DB=$DBName
      - POSTGRES_USER=$DBUser
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 3s
      retries: 5
      timeout: 5s
    volumes:
      - database-postgres:/var/lib/postgresql/data
    networks:
      - default

  app:
#    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DBHost=$DBHost
      - DBPort=$DBPort
      - DBUser=$DBUser
      - DBPassword=$DBPassword
      - DBName=$DBName
    depends_on:
      db:
        condition: service_healthy

volumes:
  database-postgres:

networks:
  default:
    driver: bridge