version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy


  postgres:
    image: postgres:16.3
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$DBUser
      - POSTGRES_DB=$DBName
      - POSTGRES_PASSWORD=$DBPassword
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 3s
      timeout: 5s
      retries: 5
    restart: always


  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations/postgres:/migrations
    command: -path=/migrations/ -database=postgres://$DBUser:$DBPassword@$DBHost:$DBPort/$DBName?sslmode=disable up
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy