// Code generated by Wire. DO NOT EDIT.
//go:build !wireinject
// +build !wireinject

package di

import (
	_ "github.com/lib/pq"
	"project-management/internal/api"
	"project-management/internal/api/handler"
	"project-management/internal/config"
	"project-management/internal/db"
	"project-management/internal/repository"
	"project-management/internal/service"
)

func InitializeAPI(cfg config.Config) (*http.Server, error) {
	sqlxDB, err := db.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	err = db.Migrate(sqlxDB)
	if err != nil {
		return nil, err
	}
	taskRepository := repository.NewTaskRepository(sqlxDB)
	taskService := service.NewTaskService(taskRepository)
	taskHandler := handler.NewTaskHandler(taskService)
	userRepository := repository.NewUserRepository(sqlxDB)
	userService := service.NewUserService(userRepository, taskRepository)
	userHandler := handler.NewUserHandler(userService)
	projectRepository := repository.NewProjectRepository(sqlxDB)
	projectService := service.NewProjectService(projectRepository, taskRepository)
	projectHandler := handler.NewProjectHandler(projectService)
	server := http.NewServer(taskHandler, userHandler, projectHandler)
	return server, nil
}
